# Generated by Django 3.0.6 on 2020-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Интернет', 'Интернет'), ('Мобильная связь', 'Мобильная связь'), ('Телевидение', 'Телевидение'), ('Телефон', 'Телефон')], max_length=130, verbose_name='Сервис')),
                ('category', models.CharField(max_length=130, verbose_name='Категория')),
                ('subcategory', models.CharField(blank=True, max_length=130, verbose_name='Подкатегория')),
                ('answere', models.TextField(verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=130, verbose_name='Telegram ID пользователя')),
                ('username', models.CharField(max_length=130, verbose_name='Telegram username пользователя')),
            ],
        ),
    ]
