# Generated by Django 3.0.6 on 2020-11-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20201114_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Тарифы', 'Тарифы'), ('Интернет', 'Интернет'), ('Мобильная связь', 'Мобильная связь'), ('Телевидение', 'Телевидение'), ('Телефон', 'Телефон')], max_length=130, verbose_name='Сервис')),
                ('problem', models.CharField(max_length=130, verbose_name='Проблема')),
                ('category', models.CharField(max_length=130, verbose_name='Категория')),
                ('subcategory', models.CharField(blank=True, max_length=130, verbose_name='Подкатегория')),
                ('answere', models.TextField(verbose_name='Ответ')),
                ('tags', models.TextField(verbose_name="Тэги\n(Указываются через ':')")),
            ],
        ),
        migrations.DeleteModel(
            name='questions',
        ),
    ]
