# Generated by Django 3.0.6 on 2020-11-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20201114_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Имя категории')),
                ('answere', models.TextField(verbose_name='Ответ при выборе категории')),
            ],
        ),
        migrations.CreateModel(
            name='questions1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Тарифы', 'Тарифы'), ('Интернет', 'Интернет'), ('Мобильная связь', 'Мобильная связь'), ('Телевидение', 'Телевидение'), ('Телефон', 'Телефон')], max_length=130, verbose_name='Услуга')),
                ('problem', models.CharField(max_length=130, verbose_name='Проблема')),
                ('subcategory', models.CharField(blank=True, max_length=130, verbose_name='Подкатегория')),
                ('answere', models.TextField(verbose_name='Ответ')),
                ('tags', models.TextField(verbose_name="Тэги\n    (Указываются через ':')")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='bot.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='questions',
        ),
    ]
