# Generated by Django 3.0.6 on 2020-11-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20201114_0416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions1',
            new_name='questions',
        ),
    ]
