# Generated by Django 3.0.6 on 2020-11-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20201114_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='problem',
        ),
    ]
