# Generated by Django 3.0.6 on 2020-11-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_questions_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='answere',
            field=models.TextField(blank=True, verbose_name='Ответ при выборе категории'),
        ),
    ]
