# Generated by Django 3.0.6 on 2020-11-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20201114_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Тарифы', 'Тарифы'), ('Интернет', 'Интернет'), ('Мобильная связь', 'Мобильная связь'), ('Телевидение', 'Телевидение'), ('Телефон', 'Телефон')], max_length=130, verbose_name='Услуга')),
                ('name', models.CharField(max_length=130, verbose_name='Имя категории')),
                ('answere', models.TextField(blank=True, verbose_name='Ответ при выборе категории')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='bot.Categorys1'),
        ),
        migrations.DeleteModel(
            name='Categorys',
        ),
    ]
