# Generated by Django 3.0.6 on 2020-11-14 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20201114_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Имя категории')),
                ('answere', models.TextField(blank=True, verbose_name='Ответ при выборе категории')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='bot.Categorys'),
        ),
        migrations.DeleteModel(
            name='Categorys1',
        ),
    ]
